LOG_FILE = "signals_log.csv"
STATE_FILE = "daily_signal_state.json"

MIN_TEST_ACC = 0.53

BUY_THRESHOLD = 0.66
SELL_THRESHOLD = 0.34

REQUIRE_TECHNICAL_CONFIRMATION = True

MAX_SIGNALS_PER_DAY = 5
MIN_SIGNAL_GAP_HOURS = 2
MIN_CONFIDENCE = 0.60
